### ISSUE TITLE
Pyral - rally.get request every 5 minutes failing.

### ISSUE THREAD

**Issue by anushreeapk** [RallyTools/RallyRestToolkitForPython#100]
Hi ,

I am sending a rally.get query that brings data from rally (for userstory,testcases or defects), that has been updated in the last 5 minutes. This script is running at an interval of 5 minutes.

My rally query snippet: 
now = now - datetime.timedelta(minutes = 5)
nowminusfive = now.isoformat()+'Z'
timequery = 'LastUpdateDate > '+nowminusfive
response = rally.get('Defect', fetch=fields,query =timequery,start=1)

I am running the above script every five minutes and the output is being written to a log file. When I see my log file, the following error is occurring intermittently, because of which I am losing out on the updated data in the 5 minute timebox when the error is thrown and the script fails.

Error:

Traceback (most recent call last):
  File "/root/inc_defect.py", line 40, in <module>
    rally = Rally('rally1.rallydev.com', user='ermo_rq@cisco.com', password='ermorq2014', workspace='Cisco Information Technology',project='Cisco IT Projects')
  File "/usr/local/lib/python2.7/dist-packages/pyral/restapi.py", line 228, in __init__
    self.contextHelper.check(self.server)
  File "/usr/local/lib/python2.7/dist-packages/pyral/context.py", line 146, in check
    reachable, problem = Pinger.ping(target_host)
  File "/usr/local/lib/python2.7/dist-packages/pyral/context.py", line 732, in ping
    with open(bucket, 'r') as of:
IOError: [Errno 2] No such file or directory: '.ping-bucket'

What could be the issue?

**Comment by klehman-rally** [comment]
Is it possible that you are running this in a directory that the user of the running process does not own?  
And therefore the process is unable to write/read the file named '.ping-bucket' in the current working directory?
To get around this issue completely, I'd suggest that you use the **server_ping=False** keyword argument when you obtain the Rally instance.  
`rally(Rally,..., server_ping=False)`
Be aware that with 1.2.x, the default behavior is to ping the Agile Central (aka Rally) server before attempting the send the initial request (which is why you see the traceback info).  As of 1.3.x (no ETA on that release), the default behavior will be be to **not** ping the server (although you can make it do so by supplying the server_ping=True keyword arg.  In release 2.x, the ping functionality will be removed.
Also, while I appreciate the openness of your post, you should probably _fuzz_ your actual user name and password to avoid unwanted complications...
