### ISSUE TITLE
StopIteration error when update cofig.py 

### ISSUE THREAD

**Issue by AvivCohen** [RallyTools/RallyRestToolkitForPython#111]
Hi.
I'm new with Pyral package.
I've created a simple script to display my object model:

```
import sys
from pyral import Rally, rallyWorkset
options = [arg for arg in sys.argv[1:] if arg.startswith('--')]
args    = [arg for arg in sys.argv[1:] if arg not in options]
server, user, password, apikey, workspace, project = rallyWorkset(options)
rally = Rally(server, user, password, apikey=apikey, workspace=workspace, project=project)
rally.enableLogging('mypyral.log')

projects = rally.get('HierarchicalRequirement', projectScopeDown = True, project = "myCompany");
for prj in projects:
    print(prj)
```

When I'm changing the START_INDEX parameter(config.py) to any value that is not 1, I receive from command prompt the next error:

 

> Traceback (most recent call last):
>   File "geths.py", line 6, in <module>
>     rally = Rally(server, user, password, apikey=apikey, workspace=workspace, pr
> oject=project)
>   File "C:\Python27\lib\site-packages\pyral\restapi.py", line 248, in __init__
>     self.contextHelper.check(self.server, wksp, proj, self.isolated_workspace)
>   File "C:\Python27\lib\site-packages\pyral\context.py", line 171, in check
>     self._getDefaults(user_response)
>   File "C:\Python27\lib\site-packages\pyral\context.py", line 425, in _getDefaul
> ts
>     user = user_response.next()
>   File "C:\Python27\lib\site-packages\pyral\rallyresp.py", line 258, in next
>     return self.__next__()
>   File "C:\Python27\lib\site-packages\pyral\rallyresp.py", line 272, in __next__
>     raise StopIteration
> StopIteration

From what I've read, StopIteration is signal that points where there's nothing more to produce
Why changing values in START_INDEX cause this error? 

Thanks,
Aviv

**Comment by klehman-rally** [comment]
By common convention (rather than by enforcement), an assignment to a variable in caps signifies that it is to be used a constant value.  Dipping in to a package from another program/module/package and changing the value of such a package specific var is a practice that has risks and is to be generally avoided.  With that said, the Rally.get method offers a 'start' keyword that should be used whenever you want to qualify the 'get' to those items satisfying a query whose index in the qualifying sequence starts at an index other than 1.  When provided, the value associated with the 'start' keyword is used in constructing the overall query string for the request.  The Agile Central (Rally) WS REST API does not use base-offset indexing (where the index of the first item is 0), rather it uses positive natural numbers where the first item is index 1.  Information on all of the keyword arguments available for the Rally.get method is available in the package documentation.

**Comment by AvivCohen** [comment]
Tnx @klehman-rally  !
Just to make sure I understood -  Rally.get can support this issue to extract data in? I've tested it with values **greater than 1**

**Comment by klehman-rally** [comment]
Here's a scenario...  You've a got a query condition that would result in 185 items being returned. Let's say you want item 50 through 185.  Given a pyral.Rally instance you'd issue the get thusly:
   response = rally.get('Story', query=your_query, start=50)  
and then iterate over the response to obtain the items.   
Let me know if you've got a different scenario in mind.
