### ISSUE TITLE
getAllowedValues() does not return allowed values for custom fields 

### ISSUE THREAD

**Issue by calwas** [RallyTools/RallyRestToolkitForPython#117]
This issue effectively reopens Issue #99 

I tested with 1.2.3 and 1.2.4 and 1.3.0. The results described in the original issue apply to all versions. Nothing has changed.

**Comment by klehman-rally** [comment]
I'd like to get a better understanding of your use case.  I've got a working branch on which retrieving the allowed values list on a custom attribute that is created as a "Drop Down List (Multi Value)" which in turn is identified from WSAPI as being of type "COLLECTION" is supported.  I've adjusted some of the internal mechanism to disqualify many standard attributes of the same type (COLLECTION) from chasing the collection url to get the "allowed values".  The rationale for the latter is that most of the standard attributes of COLLECTION type are not really workspace wide value collections, but rather dependent on the specific artifact, in which case it is less expensive to just get the specific attribute value off of the item as opposed to getting the schema item and running the machinery to get the allowed values for every field.

**Comment by calwas** [comment]
I use getAllowedValues() on two attributes: Milestones and a custom field we call Products. I don't know the exact type of the Products field, but in the Rally web interface, it is selected from a drop-down list of multiple string values. Over time, new values are added to the list. When retrieved using pyral, the field shows as a COLLECTION.

Walking through the pyral code, I noticed that getAllowedValues() did retrieve the allowed values for Products, but short-circuited before returning them. Instead, it returns a single-item list of True. I wrote a workaround that is based on the pyral getAllowedValues() code, but doesn't short circuit. The workaround code is in a comment in Issue #99 

To retrieve the Milestones values, I have to use a different workaround implemented in the examples/get_milestones.py code provided here on Github.

I would guess that getAllowedValues() is not a method that's called very often--probably a max of once or twice, like in my script. As such, it might not be worthwhile to attempt to improve its performance by skipping "unwanted" values (especially if those values turn out to be wanted). Even if getAllowedValues() is an expensive method, I suspect it would still take up only a small portion of the total execution time when combined with Rally.get() and other pyral methods that a typical script would call. But I'm just guessing. Did users complain about long getAllowedValues() times?

Let me know if I can provide any more information.

**Comment by calwas** [comment]
I just tried getAllowedValues() in pyral 1.3.1. The method now works as I would expect for the custom field. To retrieve the allowed Milestones values, I still need to use the get_milestones.py workaround, but I can live with that idiosyncrasy.

I think this issue can finally be closed. Thanks much for your continued attention to it.

**Comment by klehman-rally** [comment]
Glad you were able try out 1.3.1 and have it meet your needs.  To finally answer your question about whether others had performance issues with getAllowedValues, about 16 months ago the internals of AC WSAPI changed and pyral package users noticed a big performance hit on artifact updates.  The cause of that was that pyral does validation for field names and for values for fields that have an allowedValues list or collection ref.  Prior to the change in the internals in the WSAPI, only fields whose type was STATE or RATING (mostly true, there were a _few_ other fields) had allowedValues and almost universally the lists of allowed values were short.  And because of the few allowedValues fields, the validation expense pretty much was unnoticed.  After the change, quite a few fields ended up having a an allowedValues collection ref and in some cases the validation time expense went from sub-second to dozens of seconds.  In the interest of not sacrificing validation, I made some changes in pyral to "tune" the consideration of what allowedValues refs to chase that ended up breaking getting custom fields with allowedValues.  I think the sum of changes now in 1.3.1 is a fair trade-off in terms of keeping create/update field validation and the ability to get allowedValues  for fields that are valid for all of a specific entity type for a workspace.  Thanks for your tenacity in creating the problem reports and detailed information that helped in locating the root cause and designing a useful solution.
