### ISSUE TITLE
Rally.post doesn't pass its keyword args to Rally.get

### ISSUE THREAD

**Issue by c-wicklein** [RallyTools/RallyRestToolkitForPython#121]
I've modified post locally (diff below) to pass its kwargs to get so that I can use projectScopeUp and projectScopeDown with the post method.  I needed this change for a client to submit a request to change an entity's status to complete where the entity is only identified by FormattedID and the entity isn't in the current project.

```
@@ -1052,7 +1052,7 @@ class Rally(object):
                 raise RallyRESTAPIError('An identifying field (ObjectID or FormattedID) must be specified')
             fmtIdQuery = 'FormattedID = "%s"' % formattedID
             response = self.get(entityName, fetch="ObjectID", query=fmtIdQuery,
-                                workspace=workspace, project=project)
+                                workspace=workspace, project=project, **kwargs)
             if response.status_code != HTTP_REQUEST_SUCCESS_CODE or response.resultCount == 0:
                 raise RallyRESTAPIError('Target %s %s could not be located' % (entityName, formattedID))
```

**Comment by c-wicklein** [comment]
Fixed the Markdown; hopefully this makes sense now.

**Comment by klehman-rally** [comment]
The other way to address is that doesn't involve modifying pyral is to use the project=None keyword arg in the call to rally.post (aka update).  Since FormattedID values span an entire workspace, if you know the FormattedID, there can only be a single instance of an artifact with that value in the workspace.  So, by specifying that project=None, if the artifact exists, it will be found and the rest of the post method works as designed.  Of course, if you prefer the local modification continue to use that.
