### ISSUE TITLE
rally.get() not fetching all records from Rally

### ISSUE THREAD

**Issue by Athulyadas** [RallyTools/RallyRestToolkitForPython#131]
Hi,

I am trying to fetch all the records for UserStories / Defects/ Testcases from a workspace in Rally using rally.get() and push to our DB. 

Ex: rally.get('UserStory', fetch=fields, order="FormattedID",start=start, pagesize=200, limit=200)
      
But it is not fetching all records from Rally every time. At times, it fails to fetch the complete data from Rally, and does not throw any error. This results in pushing only less data to our DB where we expect whole data from Rally.

Is there could be a reason for this function to work differently each time ? Or is there any other function to fetch all records from rally other than this one.

**Comment by klehman-rally** [comment]
From your description of the situation it sounds as though network path performance is uneven or you have a large fetch list or we were having a bad day with AC availability/responsiveness.  
In your example you have a limit=200 keyword arg which would limit the result to 200 items.
I'll also point out that we have a database connector available for customers that can be used to "replicate" AC data in a Postgres DB or can be used to emit CSV files which can then be bulk loaded into some other species of DB (Oracle, SQL Server, etc) as long as there is the ability for the target DB to process CSV files.  
Another way around the problem is to "partition" your data along some dimension (State, CreationDate, Owner, etc) and engage in a divide and conquer approach, ie., making multiple requests using different query conditions to arrive at your complete set.
