### ISSUE TITLE
How can I retrive the currect iteration?

### ISSUE THREAD

**Issue by aviadraveh** [RallyTools/RallyRestToolkitForPython#141]

**Comment by aviadraveh** [comment]
I didn't find a way to get the current iteration for a workspace/project

**Comment by klehman-rally** [comment]
An Iteration entity has attributes of Project, StartDate and EndDate.  You can use a pyral Rally instance get method targeting Iteration like so:
...
rally = Rally(*your options including credentials, workspace, project, etc.)
result = rally.get('Iteration')
You could then iterate through the result, checking to see that your target date >= StartDate and target date <= EndDate (assuming your target date is today's date).  
Alternatively, you could construct query conditions that expressed the same logic and provide those to the get call so that the selection logic executes on the WSAPI receiving end.
