### ISSUE TITLE
Can't parse portfolio_item

### ISSUE THREAD

**Issue by tsal** [RallyTools/RallyRestToolkitForPython#147]
Code snippet:

```
resp = rally.get("PortfolioItem_Feature", fetch=True, query="FormattedID = \"F1234\"")
```

The "F1234" above is an example.  The above code works (swapping the entity type as appropriate), but fails when trying to search for a feature based on its formatted ID.

```
{u'QueryResult': {u'Errors': [u'Not able to parse artifact type: portfolioitem_feature'], u'_rallyAPIMinor': u'0', u'PageSize': 0, u'Warnings': [], u'_rallyAPIMajor': u'2', u'Results': [], u'StartIndex': 0, u'TotalResultCount': 0}}
```

If I'm searching for the wrong entity type, please update the documentation, it is completely unclear whether this is correct, or if it's a completely different set of calls I need to make to search for a feature.

This works with Defects, DefectSets and UserStories - I really need to be able to get the information from Feature codes, too.

**Comment by klehman-rally** [comment]
There is text in the overview mentioning operations with custom PortfolioItem sub-types and shows the syntax to be used. However, I agree that there should be some text in that document that mentions both standard and custom PortfolioItem sub-types and the syntax required to specify them.  In the 1.5.0 release I will add text to address this issue.
BTW, the correct syntax for your specific example is to use either 'Feature' or 'PortfolioItem/Feature'.  While there is code in pyral mentioning 'PortfolioItem_Feature' (and the other standard PortfolioItem sub-types)  that is not intended to be used an exemplar for using the module.  I didn't see any place in the user documentation that had that but if you find some, let me know and I'd be happy to rectify that so that there is just one approach mentioned in the documentation.
