### ISSUE TITLE
rally.get() returns wrong results for a query with char "&"

### ISSUE THREAD

**Issue by Kimudai94** [RallyTools/RallyRestToolkitForPython#157]
I want to receive all PortfolioItems of a project with the character "&". 
If I use the web version for this (https://rally1.rallydev.com/slm/doc/webservice/) it is working.

But when I try it with rally.get() it returns a empty response.
After debugging, we discovered that the replacement was the problem (pyral\query_builder.py:195). 
If we comment out this line, we get the correct results.

**Comment by klehman-rally** [comment]
This will be fixed in 1.5.0.  
For now the workaround is to set the project separately and not use the project in the query clause.
For example if your target project name is something like 'Drag&Drop', you'd execute the following:
rally.setProject('Drag&Drop') 
then your query clause for the rally.get call wouldn't have to have the 'Project = "Drag&Drop'" in it, but the resulting call will still scope to that project.
