### ISSUE TITLE
Getting error while running getAllUsers() 

### ISSUE THREAD

**Issue by saurabh-9995** [RallyTools/RallyRestToolkitForPython#162]
Retrying the page_urls for the page group startIndexes: 501 -> 5001
Retrying the page_urls for the page group startIndexes: 501 -> 5001
Retrying the page_urls for the page group startIndexes: 501 -> 5001
Traceback (most recent call last):
  File "rally.py", line 29, in <module>
    all_users = rally.getAllUsers()
  File "/usr/local/lib/python3.7/site-packages/pyral/restapi.py", line 636, in getAllUsers
    users = [user for user in response]
  File "/usr/local/lib/python3.7/site-packages/pyral/restapi.py", line 636, in <listcomp>
    users = [user for user in response]
  File "/usr/local/lib/python3.7/site-packages/pyral/rallyresp.py", line 313, in __next__
    self._page[:]  = self.__retrieveNextPage()
  File "/usr/local/lib/python3.7/site-packages/pyral/rallyresp.py", line 410, in __retrieveNextPage
    chapter = self.__retrievePages()
  File "/usr/local/lib/python3.7/site-packages/pyral/rallyresp.py", line 478, in __retrievePages
    raise RallyResponseError("Unable to retrieve %d chunks of data" % num_threads)
pyral.rallyresp.RallyResponseError: Unable to retrieve 10 chunks of data

**Comment by saurabh-9995** [comment]
Hey team, can you please help me with this query? Thanks!
@klehman-rally

**Comment by klehman-rally** [comment]
This issue is very similar to issues raised in the past.  I am unable to reproduce this issue on the Subscriptions I have access to (which have 2000 or fewer User instances).  The output which mentions 'Retrying the page_urls for the page group startIndexes: 501 -> 5001' would seem to imply that your target Subscription has more than 5000 User instances.   
The getAllUsers is a convenience method that uses the Rally.get method underneath.  One approach you could take is to is to subdivide the universe of Users to consider only the instances whose Disabled attribute is False.  Get the total result count and then issue individual requests for a block of users (setting a reasonable pagesize of 100, a specific start value, and a limit).  This approach is untested and places the burden of organization/management on you the developer.  
If you go this route and also need to get the Disabled = True User items, the process is identical, only the query criteria changes.
