### ISSUE TITLE
get User call doesn't fetch all user fields using pyral

### ISSUE THREAD

**Issue by Pravesh-dot-com** [RallyTools/RallyRestToolkitForPython#167]
I am trying to fetch all users data with all the fields that I can see with .typedef method for users. 
To name a few - 
CreationDate
c_TestLocation  
c_TestRole  
c_WorkStatus

I tried the following ways.

1. Using Convenience method
rally.getallusers() - This gives an error. 
pyral.rallyresp.RallyResponseError: Unable to retrieve 2 chunks of data
I assumed since I am no admin, I might not have sufficient privileges for this to run.

2. using Get call with filter for creation date.

create_dt = "2010-01-10T00:00:00.000Z"
query = '(CreationDate > "{}")'.format(create_dt)
response = rally.get('User', fetch = True, query = query, projectScopeDown=True, limit=100)
for i in response:
    print(i.CreationDate)

Error - raise AttributeError(description)
AttributeError: User instance has no attribute: 'CreationDate'

Here, I get all the users' data. Although, I am able to fetch other fields like Username, email etc but not the ones that I have mentioned above.

3. Using Get call without any filter
response = rally.get('User', fetch = True, projectScopeDown=True, limit=500)

Here, I get all the fields that I am looking for. But, there is only one record ( which is mine i.e. my user information). The result is a dict.

Is there a way/hack/trick to get all the users' fields depending on the filter in the query ?

Please let me know if any other information is required.

**Comment by klehman-rally** [comment]
As you have surmised, unless the user you've authenticated with is a Subscription Admin then you won't have sufficient privileges to get all the data you are after.  While I don't have a clear picture on what your scenario/use-case is, keep in mind that the pyral package was not designed with the intent of supplying all the functionality a comprehensive user admin tool might need.
With that said, since you mentioned that approach number 2 retrieved information about all users (but without some of the attributes you are specifically wanting) you might try running a second query with the fetch value containing specific fields (like CreationDate, c_SomeField, c_OtherCustomField, etc).  I'm not sure about the other entities in Rally, but with User the fetch=True doesn't return the CreationDate attribute.  Once you have the results of the 2 get calls, you could do your own "join" operation in your code to augment the results of the first get with the CreationDate of the corresponding item in the results of the second get.  Note that just like your get call in number 2 has a non-empty query condition, you'll have to also supply that same condition in the get call with the specific fetch list to get a truly "parallel" duo of results on which you'd do the "join".
Hope this helps.
