### ISSUE TITLE
Project is required when I tried to query through Pyral. However, Project is not required in Rally REST API.

### ISSUE THREAD

**Issue by Linlin-Li-1** [RallyTools/RallyRestToolkitForPython#180]
Hello, 

I would like to fetch all defects within my workspace, regardless of their current project, how can I do that? 

When I tried to configure it through the Rally command without specifying project (such as `Rally(server=args['server'], apikey=args['apikey'], workspace=args['workspace']`), then it will only consider defects whose Project is 'None'. However, I would like to consider all defects within my workspace. Basically, my requirement is like `Project != null`. 

I would much appreciate it if you could help. 

Thank you,
Linlin

**Comment by klehman-rally** [comment]
By providing a project=None in the get request you can have the retrieval scoped at the workspace level.
Example:  obtain a Rally instance in the usual way (rally = Rally(args including or excluding a project)) and use it:
response = rally.get('Defect', fetch='Name,Severity,Owner,....', project=None) 
I would encourage use of a relatively small list of attributes rather than use fetch=True and possible query criteria that limits the population to items of interest.  I don't how many projects are in your workspace of interest or how heavily populated that workspace is in terms of artifacts of interest, but you should be aware that Rally will throttle requests that are resource intensive at a certain point.  Hope this helps...

**Comment by Linlin-Li-1** [comment]
Thanks Kip, it works.
