### ISSUE TITLE
Support for RecycleBinEntry

### ISSUE THREAD

**Issue by amcolosk** [RallyTools/RallyRestToolkitForPython#43]
Currently when I try to use RecycleBinEntry in a query , I get the error: "pyral.entity.InvalidRallyTypeNameError: RecycleBinEntry"

Looking in entity.py, it appears that it is set to never be found.  I am assuming that is because it is not supported.  Can it get added?

**Comment by fruch** [comment]
I'm guessing cause it's new...

**Comment by klehman-rally** [comment]
Support for RecycleBinEntry was left out intentionally.  One of the reasons for that was to avoid exposing a functionality (delete) that would destroy the last means of recovering a deleted item.  I'm reluctant to offer the rope on that aspect. But, the prospect of having a means to 'get' RecycleBinEntries can certainly be revisited.  I'd be interested in understanding the scenario in which you'd use a RecycleBinEntry 'get' mechanism.  The items in the RecycleBin are not full entities, they have a greatly reduced set of attributes, so any 'get' operation would end up returning 'RecycleBinEntry' items rather than 'Defect' or 'Story' items.

**Comment by klehman-rally** [comment]
Rudimentary support for GET on RecycleBinEntry now available in 1.1.1.
