### ISSUE TITLE
Support for getting "SchedulableArtifact" to allow getting stories and defects from an iteration

### ISSUE THREAD

**Issue by patknight** [RallyTools/RallyRestToolkitForPython#47]
Low priority and more a discussion point at this stage.

I'd like to get all the stories and defects delivered in an iteration in a single list (to reflect priority order.) I can get them as two separate queries (on 'HierarchicalRequirement' and 'Defect'), but because 'SchedulableArtifact' isn't a concrete class, pyral blocks it. The query on 'SchedulableArtifact' works when I test it in the Rally WSAPI page and returns the list I need.

So my question really is, is this too niche to be worth pursuing and I should just run two queries? Given that the result of the query contains the type information, instantiating the correct concrete entities (HierarchicalRequirement or Defect) from the returned JSON is in principle do-able.

What do people think?

**Comment by klehman-rally** [comment]
In investigating some of the other issues that have come up since the 1.1.0 release, I noted that pyral's entity class hierarchy was missing the SchedulableArtifact abstract class and I'm planning on putting that in the next increment (probably designated 1.1.1).  Off the top of my head, I don't know if that will result in pyral allowing SchedulableArtifact as a valid entity type argument for the get method, although I vaguely recall some previous success running a get on 'Artifact'.  It definitely seems that being able to get SchedulableArtifacts conforming to some criteria and having the correct concrete instance type in the response would qualify as being more user-friendly.  If this ends up being low hanging fruit, then I'll attempt to get it in the next increment.

**Comment by patknight** [comment]
I've coded up to get the stories then the defects for now. Unless my users need to see the iteration content in rank order (and won't go to the Web UI), this is very low priority.

**Comment by klehman-rally** [comment]
Ability to to query for SchedulableArtifact added in 1.1.1.  Also added an example script in the examples subdir named get_schedulable_artifacts.py.
