### ISSUE TITLE
Support for Collection objects

### ISSUE THREAD

**Issue by rmcfatter** [RallyTools/RallyRestToolkitForPython#56]
In pyral 1.1.1, I don't see any mention of a method to modify many-to-many relationships, such as Project-SCMRepository or Changeset-Artifact.  At least it doesn't appear to be documented.

Adding a list of object references in a post() or update() call doesn't seem to have any effect, but the
underlying API does support modifying Collections via the Collection URL for that type.  What I was
hoping to find in pyral was an equivalent add() and remove() method.  Am I missing something?

**Comment by klehman-rally** [comment]
You are correct, there is no current support in pyral for adding or removing items from a collection.  The workaround is to specify the entire collection with all the items you want as the result.  To add an item to a collection you need to obtain the members of the collection (refs) and then add the ref to the additional item you want in the collection then update the target item holding the collection. To remove an item from a collection, you will need to obtain the collection members (refs) and then remove the ref of the item targeted for removal and then update the target item holding the collection.  If this doesn't address your problem, please provide a more specific scenario so that I can reproduce your behavior to see if your specific use case can be addressed or that a workaround is feasible.

**Comment by klehman-rally** [comment]
Investigation of this turned up the sad truth that collections in the CA Agile Central data model are not implemented in a uniform manner.  Some collections  exist in a two-way relationship (e.g., Artifact-Changeset), and some exist  in a one-way relationship (SCMRepository - Project).
There wasn't an obvious clean implementation path, and the most initially appealing approach of adding the add and remove method to AgileCentral datamodel subclasses of WorkspaceDomain objects had some unpleasant or high-effort related downside.
While I agree that having add/remove methods related to collection manipulationwould be desirable from a intuitive use perspective, there's just more effort  required than I'm willing to spend on this at this point.
