### ISSUE TITLE
Pyral with Multithreading 

### ISSUE THREAD

**Issue by anushreeapk** [RallyTools/RallyRestToolkitForPython#85]
Hi!
I've implemented multithreading using pyral for the rally.get command wherein each thread fetched 200 records from rally by changing the start parameter (1,201,401 etc..) . Therefore, all my threads are pulling rally records in batches of 200.
However,these rally.get requests are behaving intermittently where some of them throw an error and do not return any response . 

Here's the error I've caught for the failed get requests from some of the threads: -

Exception in thread Thread-249:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 808, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 761, in run
    self.__target(*self.__args, **self.__kwargs)
  File "testcase_ciscoit.py", line 51, in m
    for case in response:
  File "/Library/Python/2.7/site-packages/pyral/rallyresp.py", line 266, in next
AttributeError: 'RallyRESTResponse' object has no attribute '_served'

What could be the possible reason ? Attached is the code I'm running
[pyral_multithread_code.txt](https://github.com/RallyTools/RallyRestToolkitForPython/files/368475/pyral_multithread_code.txt)

**Comment by klehman-rally** [comment]
The pyral package was not designed to be thread-safe (on purpose); Threading can be tricky. 
In order to successfully deal with the intermittent  error (originating in the CA Agile Central WSAPI) you'd have to catch that and retry using some sort of limited-attempt back-off strategy (like a sleep if 0.2, 0.7, 1.3 secs) to make sure that each of your threads obtained the information satisfying the GET request.
I will consider providing automatic package support for threading to increase performance for the retrieval of large sets of data (> 1000 elements) in a future release.
